version: '3'
services:
  mongo:
    image: mongo:4
    container_name: "elepy-docs-db"
    restart: always
    volumes:
      - /home/kumiryan/elepy-docs/data:/data/db
    networks:
      - tls
  elepy-docs:
    restart: always
    build: .
    container_name: "elepy-docs"
    image: elepy-docs
    networks:
      - tls
    environment:
      - DATABASE_SERVER=elepy-docs-db
    ports:
      - "4242:4242"
    links:
      - mongo
    depends_on:
      - mongo
networks:
  tls:
    external: true